### PR TITLE
Use urgency level

### PR DESCRIPTION
**Pull request by oz123**
If the command succeeded the level is normal, so the UI is colored
 blue, else the level is critical and the UI is red.
screenshot at 2016-07-25 16-10-47
screenshot at 2016-07-25 16-11-12

As is in the photos.

### CODE REVIEW

**Comment by jungle-boogie** [comment]
How does ntfy know what's failed? I thought I mentioned a failure is shown as a success a few months back.

**Comment by oz123** [comment]
The [return code](https://github.com/dschep/ntfy/blob/master/ntfy/cli.py#L37 ) of the process is the indicator for failure or success, upon which the [message is determined](https://github.com/dschep/ntfy/blob/master/ntfy/cli.py#L57). 

Normal behaving software in UNIX and Linux return 0 if no errors where encountered.

**Comment by dschep** [comment]
You're right that ntfy uses the return code, but this diff is checking the message string and would cause priority hints for any message containging the word failed, such as `ntfy send "nothing failed!"` or `ntfy done echo failed`.

If all the `notify()` functions accepted an optional argument for return code or a sort of success hint, i'd be cool with that (it could set of the `priority` argument of the Pushover backend if the use doesn't specify it too).

Mildly off topic: what notification daemon are you using. The notifications look identical for me in LXDE on Fedora when setting urgency (I was testing with `notify-send -u critical foobar`

**Comment by oz123** [comment]
Let's start with the easy answers first: I am using mate-desktop, so it's just the default notification that comes with GTK\GNOME\MATE.
Second, I have modified the code such that retcode is passed on to the function `notify`. I have also updated the tests where needed. However, one stubborn test is still failing, even without my changes. Which quite puzzles me ... I am pushing the changes with the expectation it will not pass the tests, but maybe you can help me fix it, see the log of running the tests locally on my laptop:

```
(ntfy)  oznt@laptop-oz:~/Software/ntfy  [master]  $ git reset --hard origin/master 
HEAD is now at afb7cb4 link latest docs
(ntfy) oznt@laptop-oz:~/Software/ntfy  [master]  $ python setup.py test
running test
Searching for psutil
Best match: psutil 4.3.0
Processing psutil-4.3.0-py2.7-linux-x86_64.egg

Using /home/oznt/Software/ntfy/.eggs/psutil-4.3.0-py2.7-linux-x86_64.egg
Searching for emoji
Best match: emoji 0.3.9
Processing emoji-0.3.9-py2.7.egg

Using /home/oznt/Software/ntfy/.eggs/emoji-0.3.9-py2.7.egg
Searching for sleekxmpp
Best match: sleekxmpp 1.3.1
Processing sleekxmpp-1.3.1-py2.7.egg

Using /home/oznt/Software/ntfy/.eggs/sleekxmpp-1.3.1-py2.7.egg
Searching for mock
Best match: mock 2.0.0
Processing mock-2.0.0-py2.7.egg

Using /home/oznt/Software/ntfy/.eggs/mock-2.0.0-py2.7.egg
Searching for six>=1.9
Best match: six 1.10.0
Processing six-1.10.0-py2.7.egg

Using /home/oznt/Software/ntfy/.eggs/six-1.10.0-py2.7.egg
Searching for pbr>=0.11
Best match: pbr 1.10.0
Processing pbr-1.10.0-py2.7.egg

Using /home/oznt/Software/ntfy/.eggs/pbr-1.10.0-py2.7.egg
Searching for funcsigs>=1
Best match: funcsigs 1.0.2
Processing funcsigs-1.0.2-py2.7.egg

Using /home/oznt/Software/ntfy/.eggs/funcsigs-1.0.2-py2.7.egg
running egg_info
writing requirements to ntfy.egg-info/requires.txt
writing ntfy.egg-info/PKG-INFO
writing top-level names to ntfy.egg-info/top_level.txt
writing dependency_links to ntfy.egg-info/dependency_links.txt
writing entry points to ntfy.egg-info/entry_points.txt
reading manifest file 'ntfy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ntfy.egg-info/SOURCES.txt'
running build_ext
test_eventhandler (tests.test_xmpp.NtfySendMsgBotTestCase) ... ok
test_start (tests.test_xmpp.NtfySendMsgBotTestCase) ... ok
test_start_mtype (tests.test_xmpp.NtfySendMsgBotTestCase) ... ok
test_capath (tests.test_xmpp.XMPPTestCase) ... ok
test_backwards_compat (tests.test_config.TestLoadConfig) ... No handlers could be found for logger "ntfy.config"
ok
test_default_config (tests.test_config.TestLoadConfig) ... ok
test_open_error (tests.test_config.TestLoadConfig) ... ok
test_parse_error (tests.test_config.TestLoadConfig) ... ok
test_darwin (tests.test_integration.TestIntegration) ... ok
test_default (tests.test_integration.TestIntegration) ... ok
test_linux (tests.test_integration.TestIntegration) ... ok
test_pushbullet (tests.test_integration.TestIntegration) ... ok
test_pushover (tests.test_integration.TestIntegration) ... ok
test_win32 (tests.test_integration.TestIntegration) ... ok
test_xmpp (tests.test_integration.TestIntegration) ... ok
test_shellintegration_printout (tests.test_cli.ShellIntegrationTestCase) ... export AUTO_NTFY_DONE_LONGER_THAN=-L<MagicMock name='mock.longer_than' id='140016815344656'>
export AUTO_NTFY_DONE_UNFOCUSED_ONLY=-b
source /home/oznt/.local/share/ntfy/auto-ntfy-done.sh
# To use ntfy's shell integration, run this and add it to your shell's rc file:
# eval "$(ntfy shell-integration)"
ok
test_args (tests.test_cli.TestMain) ... ok
test_default (tests.test_cli.TestRunCmd) ... ok
test_emoji (tests.test_cli.TestRunCmd) ... ok
test_longerthan (tests.test_cli.TestRunCmd) ... ok
tests_usage (tests.test_cli.TestRunCmd) ... usage: ntfy done [-h|-L N] command
ntfy done: error: the following arguments are required: command
ok
test_watch_bad_pid (tests.test_cli.TestWatchPID) ... ERROR: PID 100000 not found
ok
test_watch_pid (tests.test_cli.TestWatchPID) ... ok
test_basic (tests.test_pushover.TestPushover) ... ok
test_device (tests.test_pushover.TestPushover) ... ok
test_hi_priority (tests.test_pushover.TestPushover) ... ERROR: retry is less than 30 or is not set, setting retry to 30 to comply with pushover API requirements
ERROR: expire is greater than 86400 seconds or is not set,setting expire to 86400 to comply withpushover API requirements
ok
test_hi_priority_callback (tests.test_pushover.TestPushover) ... ERROR: retry is less than 30 or is not set, setting retry to 30 to comply with pushover API requirements
ERROR: expire is greater than 86400 seconds or is not set,setting expire to 86400 to comply withpushover API requirements
ok
test_hi_priority_expire (tests.test_pushover.TestPushover) ... ERROR: retry is less than 30 or is not set, setting retry to 30 to comply with pushover API requirements
ok
test_hi_priority_retry (tests.test_pushover.TestPushover) ... ERROR: expire is greater than 86400 seconds or is not set,setting expire to 86400 to comply withpushover API requirements
ok
test_html (tests.test_pushover.TestPushover) ... ok
test_invalid_priority (tests.test_pushover.TestPushover) ... ok
test_priority (tests.test_pushover.TestPushover) ... ok
test_sound (tests.test_pushover.TestPushover) ... ok
test_url (tests.test_pushover.TestPushover) ... ok
test_url_title (tests.test_pushover.TestPushover) ... WARNING: url_title specified without specifying url
ok
test_basic (tests.test_pushbullet.TestPushbullet) ... ok
test_device (tests.test_pushbullet.TestPushbullet) ... ok
test_email (tests.test_pushbullet.TestPushbullet) ... ok
test_backenderror (tests.test_ntfy.ErrorTestCase) ... FAIL
test_invalidbackend (tests.test_ntfy.ErrorTestCase) ... ERROR: failed to load backend foobar
Traceback (most recent call last):
  File "/home/oznt/Software/ntfy/ntfy/__init__.py", line 21, in notify
    module = import_module('ntfy.backends.{}'.format(backend))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named foobar
ok
test_runcmd (tests.test_ntfy.OverrideBackendTestCase) ... ok

======================================================================
FAIL: test_backenderror (tests.test_ntfy.ErrorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oznt/Software/ntfy/.eggs/mock-2.0.0-py2.7.egg/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/oznt/Software/ntfy/tests/test_ntfy.py", line 30, in test_backenderror
    self.assertEqual(ret, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 41 tests in 0.148s

FAILED (failures=1)

```

**Comment by dschep** [comment]
I'll have to look more closely when I get in front of a computer, but this new change looks great. I'll try to get the tests passing too.

**Comment by oz123** [comment]
@dschep sorry for all the noise... Despite what CI says, the test should pass.

**Comment by oz123** [comment]
@dschep Finally! It took me a while... I am sorry for such complicated history. If you want I can squash all the commits to one commit (although, I think it's better not too... because the history with appveyor should stay, maybe other people will find these messages useful). 

Hopefully, you will find these changes acceptable! Having the notifications OSD use different colors helps me quickly determine whether a command failed or succeeded without needing to read the whole message.

**Comment by jungle-boogie** [comment]
So if someone writes this, what color would your notification be?

`ntfy done rm -rf /`

**Comment by dschep** [comment]
I like it! Great work wrangling AppVeyor :smiley:

I need to see if I can get my notification deamon to use a different theme (or at least show _some_ indication of urgency hints).

**Comment by dschep** [comment]
Oh. @oz123, meant to ask. What's the reason for the different handling for `exc_info` in py35? AFAICT the only documented difference is that `.error()` accepts `exc_info` as an exception starting in 3.5, but you're only passing a boolean regardless.

**Comment by sambrightman** [comment]
It looks like only the Linux backend is doing this auto-raise of priority. Some others use a different emoji though. Is the inconsistency acceptable? Should other backends also raise the priority on failure?

**Comment by dschep** [comment]
Yeah, not a bad idea @sambrightman, the main reason I didn't do that tho is the implications of priorities aren't the same for various platforms. I was cool with this bc AFAICT the only thing it does is a small visual cue(that doesn't even show with my notification daemon.. kinda with it did! :laughing:) For example, with pushover, hi-pri notifications ignore quiet hours.

**Pull request merged**
