### PR TITLE
shell integration for bash & zsh!

### PR DESCRIPTION
**Pull request by dschep**
Uses https://github.com/rcaloras/bash-preexec in bash

Todo:
- [x] Document
- [x] Tests
- [x] Feedback?

### CODE REVIEW

**Comment by dschep** [comment]
If anyone wants to test this, install the `auto-ntfy-done` branch from github it like this:
```
sudo pip3 install -U git+https://github.com/dschep/ntfy@auto-ntfy-done#egg=ntfy
```

**Comment by jungle-boogie** [comment]
This is now either failing because I have xmpp + auto-notify or something broke the integration...

```
% ntfy done date
Mon Feb 22 18:49:18 PST 2016
Traceback (most recent call last):
  File "/usr/local/bin/ntfy", line 9, in <module>
    load_entry_point('ntfy==1.1.1.post1', 'console_scripts', 'ntfy')()
  File "/usr/local/lib/python3.4/site-packages/ntfy/cli.py", line 181, in main
    message = args.func(args)
  File "/usr/local/lib/python3.4/site-packages/ntfy/cli.py", line 24, in run_cmd
    if duration <= args.longer_than:
TypeError: unorderable types: float() <= NoneType()
```

**Comment by dschep** [comment]
Ah, that's unrelated to this branch but is a bug I fixed in master. I'll be merging this branch into master in a second and cutting a new release (`v1.2.0`) once I verify that bug is really fixed. Just install that when I'm done and all should be good :smile:

**Comment by dschep** [comment]
Thanks for reporting that @jungle-boogie, It was still present in the master branch too! It's fixed now tho. Just install `v1.2.0` and you'll have shell integration and that bug will be fixed.

**Comment by jungle-boogie** [comment]
Well I think we may have an xmpp issue.

```
% ntfy --version
1.2.0
```

```
---
backends:
        - pushover
        - xmpp
pushover:
        user_key: 2600
xmpp:
         jid: "jungle-boogie@jit.si"
         password: "xxxx"
         mtype: "chat"
         recipient: "me@jit.si"
```

```
% ntfy done date
Mon Feb 22 19:51:12 PST 2016
Traceback (most recent call last):
  File "/usr/local/bin/ntfy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/ntfy/cli.py", line 192, in main
    return notify(message, args.title, config, **dict(args.option))
  File "/usr/local/lib/python3.4/site-packages/ntfy/__init__.py", line 28, in notify
    module = import_module('ntfy.backends.{}'.format(backend))
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/site-packages/ntfy/backends/xmpp.py", line 3, in <module>
    import sleekxmpp
  File "/usr/local/lib/python3.4/site-packages/sleekxmpp/__init__.py", line 20, in <module>
    from sleekxmpp.stanza import Message, Presence, Iq
  File "/usr/local/lib/python3.4/site-packages/sleekxmpp/stanza/__init__.py", line 10, in <module>
    from sleekxmpp.stanza.error import Error
  File "/usr/local/lib/python3.4/site-packages/sleekxmpp/stanza/error.py", line 9, in <module>
    from sleekxmpp.xmlstream import ElementBase, ET
  File "/usr/local/lib/python3.4/site-packages/sleekxmpp/xmlstream/__init__.py", line 14, in <module>
    from sleekxmpp.xmlstream.xmlstream import XMLStream, RESPONSE_TIMEOUT
  File "/usr/local/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 40, in <module>
    from sleekxmpp.xmlstream.resolver import resolve, default_resolver
  File "/usr/local/lib/python3.4/site-packages/sleekxmpp/xmlstream/resolver.py", line 37, in <module>
    import dns.resolver
  File "/usr/local/lib/python3.4/site-packages/dns/resolver.py", line 32, in <module>
    import dns.flags
  File "/usr/local/lib/python3.4/site-packages/dns/flags.py", line 51, in <module>
    _by_value = dict([(y, x) for x, y in _by_text.iteritems()])
AttributeError: 'dict' object has no attribute 'iteritems'
```

NOT having the xmpp stuff in the yml will result in the delivery to pushover without errors:

```
 % ntfy done date
Mon Feb 22 19:51:57 PST 2016
```

From pushover:
```
sean@lysander-fbsd:/usr~
From ntfy on 2016-02-22 at 19:51
"date" succeeded in 0:00 minutes
```

**Comment by dschep** [comment]
Hmm. From the traceback it looks like something is wrong with dnspython on your computer. It doesn't seem to be ntfy's fault. You could try reinstalling it?
If you're using python2: `sudo pip uninstall dnspython && pip install dnspython`
If you're using python3: `sudo pip3 uninstall dnspython3 && pip install dnspython3`

**Comment by jungle-boogie** [comment]
you're a lifesaver! thanks for the pointer!

**Pull request merged**
