### PR TITLE
Add Pushalot backend

### PR DESCRIPTION
**Pull request by mlesniew**
Added basic Pushalot support and tests.

### CODE REVIEW

**Comment by dschep** [comment]
Would it make sense to default image to https://cdn.rawgit.com/dschep/ntfy/master/ntfy/icon.png

**Comment by mlesniew** [comment]
Sure, we could do that, here's how it looks like in the mobile app http://imgur.com/a/7KHzK.

**Comment by dschep** [comment]
Hmm. that border looks a bit odd. Do notifications on WinPho not usually have icons associated with them?

**Comment by mlesniew** [comment]
Push notifications usually have icons in the notification area, but we can't change these.  Here we will only see the Pushalot app icon (the blue square with the cloud and the arrow).  The icon associated with the notification itself will only be  displayed after opening the Pushalot app.  

Unfortunately I don't think we can remove the border...

**Comment by dschep** [comment]
K. Gonna merge it with out using a default for `image`.

**Pull request merged**
