### PR TITLE
Added and option to hide the executed command in notifications

### LINKED ISSUE #134: Add option to not include the command run in `ntfy done` notifications
It would be nice to have the option to not include the command that was run inside of a `ntfy done` notification and instead just say something like "Your command..."

Use case: I don't want the exact commands I'm running to be sent to a third-party service per my employers security policies.

### PR DESCRIPTION
**Pull request by AndrewGuenther**
Fixes #134

### CODE REVIEW

**Comment by AndrewGuenther** [comment]
Since the documentation seems a bit spread through the README and some of the options look like they aren't documented I figured I would wait and defer to @dschep for what to do there

**Comment by dschep** [comment]
Looks great. yeah.. i generally need to improve the docs.

**Comment by AndrewGuenther** [comment]
Cool, is there anything you want me to do on my end or are we good to merge?

**Comment by dschep** [comment]
Nope 👍

**Comment by jungle-boogie** [comment]
It looks like this is merged but I don't see any new help tags on how to use it:

```
 ntfy
usage: ntfy [-h] [-c CONFIG] [-b BACKEND] [-o key value]
            [-l {CRITICAL,ERROR,WARNING,INFO,DEBUG}] [-v] [-q] [--version]
            [-t TITLE]
            {send,done,shell-integration} ...

Send push notification when command finishes

positional arguments:
  {send,done,shell-integration}
    send                send a notification
    done                run a command and send a notification when done
    shell-integration   automatically get notifications when long running
                        commands finish

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        config file to use (default:
                        /home/sean/.config/ntfy/ntfy.yml)
  -b BACKEND, --backend BACKEND
                        override backend specified in config
  -o key value, --option key value
                        backend specific options
  -l {CRITICAL,ERROR,WARNING,INFO,DEBUG}, --log-level {CRITICAL,ERROR,WARNING,INFO,DEBUG}
                        Specify the how verbose CLI output is (default:
                        WARNING)
  -v, --verbose         a shortcut for --log-level=DEBUG
  -q, --quiet           a shortcut for --log-level=CRITICAL
  --version             show program's version number and exit
  -t TITLE, --title TITLE
```

```
% ntfy --version
2.4.2
```

is the flag hidden?

**Comment by dschep** [comment]
@jungle-boogie, it's a flag of `ntfy done`:
```
$ ntfy done -h
usage: ntfy done [-h] [-L N] [-b] [--formatter command retcode duration] [-o]
                 [-e] [-H]
                 ...

positional arguments:
  command               command to run

optional arguments:
  -h, --help            show this help message and exit
  -L N, --longer-than N
                        Only notify if the command runs longer than N seconds
  -b, --background-only
                        Only notify if shell isn't in the foreground
  --formatter command retcode duration
                        Format and send cmd, retcode & duration instead of
                        running command. Used internally by shell-integration
  -o, --stdout          Capture and send standard output
  -e, --stderr          Capture and send standard error
  -H, --hide-command    Do not display the executed command in any
                        notifications
```

Also, it's only in master, not released yet (tho I think you run off master iirc)

**Comment by jungle-boogie** [comment]
could you please remind me how I can get trunk?
I did this:
cloned repo
sudo pip3 install -U .

and
cloned repo
sudo python3 setup.py install

Thanks!

**Comment by AndrewGuenther** [comment]
I installed via:

```
sudo pip install git+https://github.com/dschep/ntfy.git@18fa9f92842417ad8e35aae7cb6f780e03646925
```

Which is the SHA at tip of master right now. Works fine for me and the option properly shows up in the help.

**Comment by dschep** [comment]
All three of those options should work :)

**Comment by jungle-boogie** [comment]
thanks for the help. I've got it now!

**Pull request merged**
