### PR TITLE
add Telegram support (closes #66)

### LINKED ISSUE #66: Telegram support
ntfy is nifty. Are you interested in adding support for [Telegram](https://telegram.org/)? I made a [package](https://github.com/rahiel/telegram-send) that could be used. It has a `configure` function to guide users in setting it up and a `send` function to send stuff.
```python
conf = "~/.config/ntfy/telegram-send.conf"
telegram_send.configure(conf)
telegram_send.send(messages=["hello"], conf=conf)
```
That call to `configure` saves the credentials (api token, and which user to send messages to) in the `conf` file and the call to `send` uses it to send a message.

I'd like to help if you're interested.

### PR DESCRIPTION
**Pull request by rahiel**
This adds support for Telegram.

### CODE REVIEW

**Comment by dschep** [comment]
Looks good to me! I'll install telegram to test it myself and if it works as expected I'll merge it :smiley:

**Comment by dschep** [comment]
Is `telegram_send` Py3k only?

**Comment by dschep** [comment]
Merge rahiel/telegram-send#1 and cut a new release of `telegram-send` and I'll merge!

**Comment by rahiel** [comment]
Thanks for the PR! I've released a new version with python 2 support.

**Pull request merged**
